GATEHOME=/home/jdb/bin/gate-7.0-build4195-ALL/
ONTCP=/home/jdb/workspace/OntologyLearningTool/bin/
CLASSPATH=$ONTCP:$GATEHOME/bin/gate.jar:$GATEHOME/lib/*
MAINCLASS=uk.co.jbothma.olt.CorpusMaker
CORPDIR=$1
POPULATEDIR=$2
EXTENTION=$3
STARTMEM=500m
MAXMEM=3G
java -Xms$STARTMEM -Xmx$MAXMEM -cp $CLASSPATH $MAINCLASS $CORPDIR $POPULATEDIR $EXTENTION
